### ISSUE TITLE
Can't seem to get past this error

### ISSUE THREAD

**Issue by kional** [diracdeltas/spleeter4max#45] opened 2020-07-09 20:08 UTC
OS: Windows 10 pro
Software: Ableton 10.1
Max version 8.13
Spleeter Native

Hello Everyone

For some reason spleeter isn't working correctly for me. I believe I followed all the steps correctly and even checked to make sure all the steps were taken. I have also changed the properties in the spleeter.exe located in the scripts folder to run as an administrator, but still no luck.
Please help.

![333](https://user-images.githubusercontent.com/68081708/87085950-bfaf1d80-c1fe-11ea-9731-ed6c8dbd325a.PNG)
![Inked111_n](https://user-images.githubusercontent.com/68081708/87085953-c047b400-c1fe-11ea-82de-14d96f10583b.jpg)

**Comment by diracdeltas** [comment] 2020-07-09 22:25
this is saying that Max cannot find the spleeter program. did you try enabling run as admin? #8 may have some useful tips. 

also if you open CMD.exe and type 'where spleeter' it should show where spleeter was installed.

**Comment by diracdeltas** [comment] 2020-07-09 22:27
going to close this as a duplicate of #8; please post in that thread instead since it has more windows users. i would try enabling run as admin on both spleeter and python; and then if that doesn't work, try https://github.com/diracdeltas/spleeter4max/issues/8#issuecomment-643720214

**Closed as completed by diracdeltas** 2020-07-09 22:27 UTC
Labels: duplicate
