### ISSUE TITLE
could not copy files from docker

### ISSUE THREAD

**Issue by Flatfootsam** [diracdeltas/spleeter4max#26] opened 2020-05-24 09:55 UTC
Hi guys, I downloaded Docker and Spleeter this morning and donated via Bandcamp.

I pulles an mp3 (also tried Wav) into Ableton and ran Spleeter and after a while I got the above error message. I tried putting the flie i was splitting in the Spleeter folder and also tried halving the size of it but no luck! Please help if you can. 

Thank you.

Jon (win10 pro) Ableton 10.1.4

**Comment by diracdeltas** [comment] 2020-05-24 21:50
oof unfortunately i've hit a dead end trying to investigate this. no weird errors in the max console?

**Comment by diracdeltas** [comment] 2020-05-24 21:54
if you open the max console (see readme for instructions) it should show `Error running docker cp` and the actual docker error

**Comment by diracdeltas** [comment] 2020-05-24 22:02
going to merge this as a duplicate of #4

**Closed as completed by diracdeltas** 2020-05-24 22:02 UTC
